package: demo_uikit3
version: 1.0.0-dev
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/demo_uikit3'
page:
    title: 'translate:demo_uikit3_title'
    perm: 'demo_uikit3[]'
    pjax: true
    subpages:
        install: { title: 'translate:title' }
requires:
    packages:
        backup: ^2.3.0
        structure/content: ^2.7.0
        cke5: ^5.0.0
        mform: ^6.1.2
        mblock: ^3.4.4
    redaxo: ^5.13.0
console_commands:
    'demo_uikit3:install': rex_command_demo_uikit3_install
